# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  yum:
    pkg: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq
